backend:
  name: github
  repo: martijnvdbrug/amberweel.nl

site_url: https://amberweel.netlify.com

media_folder: assets/uploads

collections: # A list of collections the CMS should be able to edit
  - name: 'Home' # Used in routes, ie.: /admin/collections/:slug/edit
    editor:
      preview: false
    label: 'Home' # Used in the UI
    label_singular: 'Home' # Used in the UI, ie: "New Post"
    extension: html
    description: >
      Hier kun je de inhoud van de Home pagina bewerken
    folder: 'pages'
    # slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    # ummary: '{{title}} -- {{year}}/{{month}}/{{day}}'
    create: false # Allow users to create new documents in this collection
    delete: false
    fields: # The fields each document in this collection have
      - { label: 'Title', title: 'title', name: 'title', widget: 'string', hint: 'Dit is de titel vanhet tablad in de browser'}
      - { label: 'Intro', title: 'intro', name: 'intro', widget: 'text' }
      - { label: 'Productie', title: 'Productie', name: 'productie', widget: 'text' }
      - { label: 'Choreograaf', title: 'Choreograaf', name: 'choreograaf', widget: 'text' }
      - { label: 'Dansdocent', title: 'Dansdocent', name: 'dansdocent', widget: 'text' }
      - { label: 'Danser', title: 'Danser', name: 'danser', widget: 'text' }
  - name: 'pages' # Used in routes, ie.: /admin/collections/:slug/edit
    editor:
      preview: false
    label: 'Paginas' # Used in the UI
    label_singular: 'Pagina' # Used in the UI, ie: "New Post"
    description: >
      Hier kunnen alle paginas, behalve de homepagina, worden bewerkt.
    folder: 'pages'
    # slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    # ummary: '{{title}} -- {{year}}/{{month}}/{{day}}'
    create: false # Allow users to create new documents in this collection
    delete: false
    fields: # The fields each document in this collection have
      - { label: 'Title', title: 'title', name: 'title', widget: 'string'}
      - { label: 'Content', title: 'Content', name: 'body', widget: 'markdown', hint: 'Dit is de inhoud van de pagina' }
